name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "apps/storybook/**"
      - "packages/ui/**"
      - ".github/workflows/deploy-storybook.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.0.0"

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/storybook/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build

      - name: Upload Storybook static files
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static
          path: apps/storybook/storybook-static

  # Deploy Job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.0.0"

      - name: Download Storybook static files
        uses: actions/download-artifact@v3
        with:
          name: storybook-static
          path: apps/storybook/storybook-static

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            apps/storybook/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        run: |
          cd apps/storybook
          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
